package com.example.domain.entities.remote

data class PeopleResponseItem(
    val affiliations: List<String> = listOf(),
    val apprentices: List<String> = listOf(),
    val armament: List<String> = listOf(),
    val born: String = "",
    val bornLocation: String = "",
    val `class`: String = "",
    val creator: String = "",
    val cybernetics: List<String> = listOf(),
    val dateCreated: Int = 0,
    val dateDestroyed: Int = 0,
    val degree: String = "",
    val destroyedLocation: String = "",
    val died: Int = 0,
    val diedLocation: String = "",
    val equipment: List<String> = listOf(),
    val era: List<String> = listOf(),
    val eyeColor: String = "",
    val formerAffiliations: List<String> = listOf(),
    val gender: String = "",
    val hairColor: String = "",
    val height: Double = 0.0,
    val homeworld: String = "",
    val id: Int = 0,
    val image: String = "",
    val kajidic: String = "",
    val manufacturer: String = "",
    val mass: Int = 0,
    val masters: List<String> = listOf(),
    val model: String = "",
    val name: String = "",
    val platingColor: String = "",
    val productLine: String = "",
    val sensorColor: String = "",
    val skinColor: String = "",
    val species: String = "",
    val wiki: String = ""
)